_ref:
  path: templates/general.yaml.njk
  vars:
    pageId: tutorial-add-blocks-config
    pageTitle: Making a booking form config
    section: Tutorial
    # prefetchPages:
    #   - tutorial-editing-page
    content:
      - id: md1
        type: Markdown
        style:
          '.markdown-body':
            fontSize: 14px
        properties:
          content:
            _ref: tutorial/tutorial-add-blocks-config-1.md
