id: tutorial-add-blocks-config
type: PageSiderMenu
public: true
properties:
  title: Making a Booking Form Config
  sider:
    width: 256px
  breadcrumb:
    list:
      - Tutorial
      - Making a Booking Form Config
areas:
  content:
    justify: center
    style:
      background: '#FFFFFF'
    blocks:
      _ref: 
        path: tutorial/template.yaml
        vars:
          title: Making a Booking Form Config
          buttons: false
          content:
            - id: md1
              type: Markdown
              properties:
                content:
                  _ref: tutorial/tutorial-add-blocks-config-1.md
